---
title: Hadrien Patte's personal site
name: Hadrien Patte
analytics: UA-146407422-1

social:
  - name: linkedin
    url: https://www.linkedin.com/in/hadrienpatte
  - name: github
    url: https://github.com/HadrienPatte
  - name: gitlab
    url: https://gitlab.com/HadrienPatte
  - name: ansible-galaxy
    url: https://galaxy.ansible.com/hadrienpatte
